services:
  # content-delivery:
  #   networks:
  #     - mangareader
  #
  # content-management:
  #   networks:
  #     - mangareader
  #
  # page-management:
  #   networks:
  #     - mangareader
  #
  # catalogue-rating:
  #   networks:
  #     - mangareader

  nginx-cache:
    image: nginx
    container_name: nginx-cache
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - mangareader

  auth:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: mangareader
      KC_DB_PASSWORD: mangareader
      KC_DB_USERNAME: mangareader
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - mangareader

  postgres:
    image: mirror.gcr.io/postgres
    environment:
      POSTGRES_DB: mangareader
      POSTGRES_USER: mangareader
      POSTGRES_PASSWORD: mangareader
    ports:
      - 5432:5432
    networks:
      - mangareader

  s3:
    container_name: s3
    image: mirror.gcr.io/minio/minio
    volumes:
      - ./s3data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mangareader

networks:
  mangareader:
    driver: bridge
