apiVersion: v1
kind: Service
metadata:
  name: catalogue-rating
  labels:
    service-name: catalogue-rating
spec:
  selector:
    service-name: catalogue-rating
  ports:
    - name: http
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-rating
  labels:
    service-name: catalogue-rating
spec:
  replicas: 2
  selector:
    matchLabels:
      service-name: catalogue-rating
  template:
    metadata:
      labels:
        service-name: catalogue-rating
    spec:
      containers:
        - name: catalogue-rating
          imagePullPolicy: Never
          image: catalogue-rating
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalogue-rating
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /catalogue-rating(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: catalogue-rating
                port:
                  number: 80
